    CREATE TABLE IF NOT EXISTS public.currency (
      symbol varchar(255) NOT NULL,
      CONSTRAINT currency_pkey PRIMARY KEY (symbol)
    );
    CREATE TABLE IF NOT EXISTS public.currency_stats (
    	price numeric(25, 7) NOT NULL,
    	date_time timestamp(6) NOT NULL,
    	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    	currency_id varchar(255) NOT NULL,
    	CONSTRAINT currency_stats_pkey PRIMARY KEY (id),
    	CONSTRAINT fk_currency_id FOREIGN KEY (currency_id) REFERENCES public.currency(symbol)
    );
    CREATE INDEX IF NOT EXISTS idx_currency_id ON public.currency_stats USING btree (currency_id);
    CREATE INDEX IF NOT EXISTS idx_date_time ON public.currency_stats USING btree (date_time);
    CREATE INDEX IF NOT EXISTS idx_price ON public.currency_stats USING btree (price);