services:
  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres_password
    ports:
      - "5432:5432"
    volumes:
      - db-vol:/var/lib/postgresql/data
    restart: always

volumes:
  db-vol:
